/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    DateInput: typeof import('./components/DateInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SurveyForm: typeof import('./components/SurveyForm.vue')['default']
    SurveyItem: typeof import('./components/SurveyItem.vue')['default']
    SurveyList: typeof import('./components/SurveyList.vue')['default']
  }
}
